server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:discodeit}}
    username: ${DB_USERNAME:discodeit_user}
    password: ${DB_PASSWORD:discodeit1234}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.sprint.mission.discodeit: info
